// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Report struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Title         string         `json:"title"`
	Content       sql.NullString `json:"content"`
	LearningNotes sql.NullString `json:"learning_notes"`
	IsHabitDone   sql.NullBool   `json:"is_habit_done"`
	IsPublic      sql.NullBool   `json:"is_public"`
	PublicToken   string         `json:"public_token"`
	SubmittedDate time.Time      `json:"submitted_date"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	GoogleID  string         `json:"google_id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type UserPublicSetting struct {
	UserID            uuid.UUID    `json:"user_id"`
	ShowTitle         sql.NullBool `json:"show_title"`
	ShowContent       sql.NullBool `json:"show_content"`
	ShowLearningNotes sql.NullBool `json:"show_learning_notes"`
	ShowHabitStatus   sql.NullBool `json:"show_habit_status"`
}
